apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "newman.fullname" . }}
  labels:
    {{- include "newman.labels" . | nindent 4 }}
  {{- if .Values.job.as_hook }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
  {{- end }}
spec:
  {{- with .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- with .Values.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "newman.labels" . | nindent 8 }}
      {{- with .Values.job.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
      - name: newman
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args: ["run", "/my_collection/collection.json"]
        volumeMounts:
        - name: data
          mountPath: "/my_collection"
          readOnly: true
      volumes:
      - name: data
        configMap:
          name: {{ include "newman.fullname" . }}
          items:
          - key: "collection.json"
            path: "collection.json"
